import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useWeb3Modal } from "@web3modal/wagmi/react";
import { signTypedData } from "@wagmi/core";
import { domain, message, types } from "@/utils";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { open } = useWeb3Modal();

  const signMessageAction = async () => {
    const signature = await signTypedData({
      domain,
      message,
      primaryType: "Inheritance",
      types,
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>Authenitcate yourself...</p>
        </div>
        <div className={styles.grid}>
          <button onClick={() => open()}>Open Connect Modal</button>
        </div>
        <div className={styles.grid}>
          <button onClick={() => signMessageAction()}>Sign message</button>
        </div>
      </main>
    </>
  );
}
